name: Template Synchronization

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
      is_force_push_pr: true
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@cf88b4ecc1bd025c198ba6ef8c56402c06103d3a # v2
        with:
          source_repo_path: position-pal/scala-template
